import {DRAGONS,SKILLS,EVENTS} from './evolution-content.js';

const root=document.querySelector('#app');
const state={level:1,xp:0,gold:30,hp:100,maxHp:100,atk:18,armor:2,rage:0,guard:0,stage:1,win:0,enemy:null,event:null,logs:[],runBest:Number(localStorage.dgBest||0),damageBonus:0};
const rand=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function log(t){state.logs.unshift(t);state.logs=state.logs.slice(0,18)}
function xpNeed(){return 35+state.level*20}
function newEnemy(){let pool=state.stage%5===0?[DRAGONS[3]]:DRAGONS.slice(0,3);let base=structuredClone(rand(pool));let scale=1+(state.stage-1)*.12;base.hp=Math.round(base.hp*scale);base.maxHp=base.hp;base.atk=Math.round(base.atk*scale);state.enemy=base;state.event=null;log(`${base.name} 출현 — ${base.trait}`);render()}
function start(){state.stage=1;state.level=1;state.xp=0;state.gold=30;state.maxHp=100;state.hp=100;state.atk=18;state.armor=2;state.rage=0;state.guard=0;state.win=0;state.damageBonus=0;log('새로운 원정이 시작됐다.');newEnemy()}
function damageEnemy(raw,ignore=0){let d=Math.max(1,Math.round(raw-Math.max(0,state.enemy.armor-ignore)));state.enemy.hp-=d;state.rage=clamp(state.rage+1,0,5);log(`용에게 ${d} 피해`);return d}
function enemyTurn(){if(!state.enemy||state.enemy.hp<=0)return;let d=Math.max(1,Math.round(state.enemy.atk-state.armor));if(state.guard){d=Math.round(d*.35);state.guard=0;log('비늘 방벽이 피해를 막았다.')}state.hp-=d;log(`${state.enemy.name}의 반격: ${d} 피해`);if(state.hp<=0){state.hp=0;state.runBest=Math.max(state.runBest,state.stage-1);localStorage.dgBest=state.runBest;log('원정 실패. 지금까지의 성장이 기록됐다.')}}
function useSkill(id){if(state.hp<=0)return;let s=SKILLS.find(x=>x.id===id);if(state.rage<s.cost){log('분노가 부족하다.');return}state.rage-=s.cost;if(id==='guard'){state.guard=1;log('비늘 방벽 전개.');enemyTurn();return}let d=damageEnemy(state.atk*s.power+state.damageBonus,id==='breath'?2:0);if(id==='drain'){let h=Math.round(d*.6);state.hp=clamp(state.hp+h,0,state.maxHp);log(`생명 포식으로 ${h} 회복`)}if(state.enemy.hp<=0)victory();else enemyTurn();render()}
function victory(){let e=state.enemy;state.win++;let gain=e.reward+state.stage*3;state.gold+=gain;state.xp+=15+state.stage*5;log(`${e.name} 격파! +${gain}G`);while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.maxHp+=12;state.hp=state.maxHp;state.atk+=3;state.armor+=1;log(`레벨 ${state.level}! 능력치가 상승했다.`)}if(state.stage%3===0){state.event=rand(EVENTS);state.enemy=null}else{state.stage++;newEnemy()}}
function eventPick(which){let ev=state.event;let effect=ev[which][2]();state.gold=Math.max(0,state.gold+effect.gold);if(effect.kind==='maxhp'){state.maxHp+=12;state.hp+=12}if(effect.kind==='heal')state.hp=clamp(state.hp+25,0,state.maxHp);if(effect.kind==='power')state.atk+=5;if(effect.kind==='relic')state.damageBonus+=3;log(`${ev.title}: ${ev[which][0]} 선택`);state.stage++;newEnemy()}
function heal(){if(state.gold<10){log('회복에는 10G가 필요하다.');render();return}state.gold-=10;state.hp=clamp(state.hp+30,0,state.maxHp);log('캠프에서 30 HP 회복');render()}
function render(){root.innerHTML=`<main class="shell"><header class="top"><div class="brand">DRAGON<span>GAME</span> / EVOLUTION</div><div class="stats"><div class="pill">Stage ${state.stage}</div><div class="pill">Lv.${state.level}</div><div class="pill">${state.gold} G</div><div class="pill">최고 ${state.runBest} Stage</div></div></header><div class="grid"><section class="card arena">${state.event?eventHTML():battleHTML()}</section><aside class="side"><section class="card"><div class="section-title">성장</div><div class="row"><b>HP</b><span>${state.hp}/${state.maxHp}</span></div><div class="bar hp"><i style="width:${state.hp/state.maxHp*100}%"></i></div><div class="row"><span>XP</span><span>${state.xp}/${xpNeed()}</span></div><div class="bar"><i style="width:${state.xp/xpNeed()*100}%"></i></div><div class="loot"><span>⚔ ${state.atk} ATK</span><span>🛡 ${state.armor} ARM</span><span>🔥 ${state.rage}/5 분노</span></div></section><section class="card"><div class="section-title">행동</div><div class="skills">${SKILLS.map(s=>`<button class="skill" data-skill="${s.id}"><b>${s.name}</b><small>${s.cost?'분노 '+s.cost+' · ':''}${s.desc}</small></button>`).join('')}</div><br><button class="btn" id="heal">캠프 회복 · 10G</button> <button class="btn primary" id="restart">새 원정</button></section><section class="card"><div class="section-title">전투 기록</div><div class="log">${state.logs.map(x=>`<div>${x}</div>`).join('')}</div></section></aside></div></main>`;bind()}
function battleHTML(){let e=state.enemy;return `<div class="enemy"><div><div class="tag">${e.name} · ${e.trait}</div><div class="dragon">${e.emoji}</div><h1>${e.name}</h1><div class="bar hp"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div><p class="muted">${Math.max(0,e.hp)} / ${e.maxHp} HP · 공격 ${e.atk}</p></div></div><div class="actions">${SKILLS.map(s=>`<button class="btn ${s.id==='breath'?'primary':''}" data-skill="${s.id}" ${state.rage<s.cost||state.hp<=0?'disabled':''}>${s.name}<br><small>${s.cost?'🔥 '+s.cost:'기본'}</small></button>`).join('')}</div>`}
function eventHTML(){let e=state.event;return `<div class="enemy"><div><span class="tag">${e.tag}</span><div class="dragon">✨</div><h1>${e.title}</h1><p class="muted">${e.text}</p><div class="actions"><button class="btn primary" data-event="a">${e.a[0]}<br><small>${e.a[1]}</small></button><button class="btn" data-event="b">${e.b[0]}<br><small>${e.b[1]}</small></button></div></div></div>`}
function bind(){document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>useSkill(b.dataset.skill));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventPick(b.dataset.event));document.querySelector('#heal').onclick=heal;document.querySelector('#restart').onclick=start}
start();
